- platform: time_date
  display_options:
    - 'time'
- platform: template
  sensors:
    vacuum_cleaner_error_sensor:
      friendly_name: Vacuum Cleaner Error Sensor
      value_template: >-
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.error is defined %}
          {{states.vacuum.xiaomi_vacuum_cleaner.attributes.error}}
        {% else %}
          No Error
        {% endif %}
