
input_boolean:
  symfonisk_volume:
    name: Symfonisk Volume
    initial: off
  symfonisk_dummy_delay:

############ Rotate to adjust volume ###########
script:
  symfonisk_lower_volume:
    sequence:
      - condition: state
        entity_id: input_boolean.symfonisk_volume
        state: 'on'
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: media_player.volume_set
        entity_id: media_player.vegantv
        data_template:
          volume_level: '{{ states.media_player.vegantv.attributes.volume_level - 0.05 }}'
      - service: script.turn_off
        entity_id: script.symfonisk_lower_volume
      - service: script.turn_on
        entity_id: script.symfonisk_lower_volume
  symfonisk_raise_volume:
    sequence:
      - condition: state
        entity_id: input_boolean.symfonisk_volume
        state: 'off'
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_dummy_delay
      - service: media_player.volume_set
        entity_id: media_player.vegantv
        data_template:
          volume_level: '{{ states.media_player.vegantv.attributes.volume_level + 0.05 }}'
      - service: script.turn_off
        entity_id: script.symfonisk_raise_volume
      - service: script.turn_on
        entity_id: script.symfonisk_raise_volume

automation:     
  - alias: symfonisk raise volume on
    initial_state: 'on'
    trigger:
    - platform: device
      domain: mqtt
      device_id: 3ee67755114e11eb9ef4c3740936b860
      type: action
      subtype: rotate_right
      discovery_id: 0xec1bbdfffe2ad31a action_rotate_right
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_volume
      - service: script.turn_on
        entity_id: script.symfonisk_raise_volume

  - alias: symfonisk raise volume off
    initial_state: 'on'
    trigger:
    - platform: device
      domain: mqtt
      device_id: 3ee67755114e11eb9ef4c3740936b860
      type: action
      subtype: rotate_stop
      discovery_id: 0xec1bbdfffe2ad31a action_rotate_stop
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_volume
      - service: input_boolean.turn_off
        entity_id: input_boolean.symfonisk_volume
          
  - alias: symfonisk lower volume on
    initial_state: 'on'
    trigger:
      - platform: device
        domain: mqtt
        device_id: 3ee67755114e11eb9ef4c3740936b860
        type: action
        subtype: rotate_left
        discovery_id: 0xec1bbdfffe2ad31a action_rotate_left
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.symfonisk_volume
      - service: script.turn_on
        entity_id: script.symfonisk_lower_volume